name: uview
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5
  - blinker=1.9.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - click=8.1.8
  - flask=3.1.0
  - importlib-metadata=8.6.1
  - itsdangerous=2.2.0
  - jinja2=3.1.6
  - ld_impl_linux-aarch64=2.43
  - libblas=3.9.0
  - libcblas=3.9.0
  - libexpat=2.6.4
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - liblapack=3.9.0
  - liblzma=5.6.4
  - libnsl=2.0.1
  - libopenblas=0.3.29
  - libsqlite=3.49.1
  - libstdcxx=14.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - markupsafe=3.0.2
  - ncurses=6.5
  - numpy=2.2.4
  - openssl=3.4.1
  - pip=25.0.1
  - python=3.11.11
  - python_abi=3.11
  - readline=8.2
  - setuptools=75.8.2
  - tk=8.6.13
  - tzdata=2025b
  - werkzeug=3.1.3
  - wheel=0.45.1
  - zipp=3.21.0
  - pip:
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - idna==3.10
      - prometheus-client==0.21.1
      - pyverbs==56.0rc5
      - requests==2.32.3
      - urllib3==2.3.0
