kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-jaeger-pvc
  namespace: {{ .Values.observability.namespace }}
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10G
